### ISSUE TITLE
Screen editor 

### ISSUE THREAD

**Issue by xHirscHx** [amauryverschooren/HASP-LVGL#1]
No issue was just wondering what program your using to edit layout on your screen.
I found i few but nothing that is in a json file type.  I'm more of a copy paste guy if i see a example i can recreate it .
The main prob is im using a 3.5 screen (wt32_sc01- 3.5). and when i find a file its for 2.5 and i have to use a lot of math to get it to look right. LOL. any help would be great 
ps have you or are you part of the /openHASP.

**Comment by amauryverschooren** [comment]
Hi @xHirscHx I'm not using a program for that? I'm just editing the json file and doing the math myself. It was a big job but got it te work in the end. If you know how much pixels you screen has, you can start calculating you sizes. 

I'm not yet part of the /openHasp i think, what is that?

Sorry for late reply, didn't touch the hasp for a while.
Greets amaury
